import express from "express"
import {body} from "express-validator"
import favoriteController from  "../controllers/favorite.controller.js"
import userController from "../controllers/user.controller.js"
import requestHandler  from "../handlers/request.handler.js"
import userModel from "../modelsuser.model.js"
import tokenMiddleware from "../middlewares/token.middleware.js"
